import { ReactNode } from "react";
import {
  CodeBracketIcon,
  CommandLineIcon,
  ShieldCheckIcon,
  CameraIcon,
  CurrencyDollarIcon,
  BanknotesIcon,
  SparklesIcon,
  GiftIcon,
  AcademicCapIcon
} from "@heroicons/react/24/outline";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faDiscord } from "@fortawesome/free-brands-svg-icons";
import { EnvelopeIcon } from "@heroicons/react/24/solid";

// ---------------------------------------------------------------------------
// Open positions - the two live development volunteer roles. Single source of
// truth for both the /contribute page and the homepage recruitment band.
// ---------------------------------------------------------------------------

export type PositionLevel = "lead" | "core";

export interface PositionBenefit {
  label: string;
  emphasis?: boolean; // visually highlighted chip (e.g. Revenue Sharing, PPT)
  headDevOnly?: boolean; // Revenue Sharing is exclusive to the Head Developer
}

export interface OpenPosition {
  id: "head-developer" | "developer"; // React key + Plausible prop + #anchor
  title: string;
  level: PositionLevel;
  levelLabel: string; // badge text, e.g. "Leadership" / "Multi-discipline"
  tagline: string; // one-liner for the homepage compact card
  description: string;
  lookingFor: string[];
  benefits: PositionBenefit[];
  formAsksFor: string; // pre-qualify microcopy
  note?: string; // Head Dev: interview-stage note
  disclaimer?: string; // Developer: volunteer-basis disclaimer
  applyHref: string; // forms.gle URL - single source of truth
  icon: ReactNode;
}

export const openPositions: OpenPosition[] = [
  {
    id: "head-developer",
    title: "Head Developer",
    level: "lead",
    levelLabel: "Leadership",
    tagline: "Lead the Dev Team across Lebuhraya, Sumaya and Bandaraya.",
    description:
      "A volunteer-with-benefits role as Head Developer of the MYSverse Dev Team. Manage our projects (Lebuhraya, Sumaya and Bandaraya) and lead the Dev Team in keeping them updated and shipping new content. You'll bridge Administration and the Dev Team, making sure both sides are heard. Fully remote, with proactive communication.",
    lookingFor: [
      "Communicate tasks, requests and information clearly and concisely",
      "Manage multiple team members with a variety of skillsets",
      "Generate new content ideas for our experiences",
      "Experienced and knowledgeable with Roblox Studio"
    ],
    benefits: [
      { label: "Revenue Sharing", emphasis: true, headDevOnly: true },
      { label: "Pay Per Task (PPT)", emphasis: true },
      { label: "Monthly Bonuses" },
      { label: "Welcome Package" },
      { label: "Professional Development" }
    ],
    formAsksFor:
      "CV/resume (PDF), full name, preferred contact, and 3 short questions.",
    note: "Accepted applicants proceed to an interview stage.",
    applyHref: "https://forms.gle/SGwBUfeM3chr2Y6j9",
    icon: <CommandLineIcon className="size-8" />
  },
  {
    id: "developer",
    title: "Developer",
    level: "core",
    levelLabel: "Multi-discipline",
    tagline: "Builders, scripters, modellers, designers and editors welcome.",
    description:
      "A volunteer-with-benefits role as a Developer of the MYSverse Dev Team. Builders, Scripters, 3D Modellers, Graphic Designers and Video Editors are all welcome. Work on current and future MYSverse experiences using your skillset and your own ideas, from updates for existing games to entirely new titles.",
    lookingFor: [
      "Creatively minded",
      "A collaborator and team player",
      "A quick learner, able to adapt",
      "Dedicated and hardworking"
    ],
    benefits: [
      { label: "Pay Per Task (PPT)", emphasis: true },
      { label: "Monthly Bonuses" },
      { label: "Welcome Package" },
      { label: "Professional Development" }
    ],
    formAsksFor:
      "Preferred name, contact, skillset, proof of work (up to 5 files), and 3 short questions.",
    disclaimer:
      "This is a volunteer-basis role. We do not offer full-time employment.",
    applyHref: "https://forms.gle/GipENfkPu181rnLg6",
    icon: <CodeBracketIcon className="size-8" />
  }
];

// ---------------------------------------------------------------------------
// Benefits at a glance - shared across both roles (Revenue Sharing is Head Dev only).
// ---------------------------------------------------------------------------

export interface Benefit {
  title: string;
  description: string;
  icon: ReactNode;
  headDevOnly?: boolean;
}

export const benefits: Benefit[] = [
  {
    title: "Revenue Sharing",
    description: "Share in the revenue generated by successful experiences.",
    icon: <CurrencyDollarIcon className="size-6" />,
    headDevOnly: true
  },
  {
    title: "Pay Per Task",
    description: "Immediate compensation upon completing a task (T&Cs apply).",
    icon: <BanknotesIcon className="size-6" />
  },
  {
    title: "Monthly Bonuses",
    description:
      "Cash bonuses tied to the success of experiences (T&Cs apply).",
    icon: <SparklesIcon className="size-6" />
  },
  {
    title: "Welcome Package",
    description: "An official MYSverse merchandise welcome package.",
    icon: <GiftIcon className="size-6" />
  },
  {
    title: "Professional Development",
    description: "Grow your skills with the wider MYSverse Network.",
    icon: <AcademicCapIcon className="size-6" />
  }
];

// ---------------------------------------------------------------------------
// Other ways to contribute - secondary, no formal application (Discord-based).
// ---------------------------------------------------------------------------

export interface Role {
  title: string;
  description: string;
  features: string[];
  icon: ReactNode;
}

export const roles: Role[] = [
  {
    title: "Moderator",
    description:
      "Be the backbone of our community. Moderators help keep MYSverse a safe, welcoming, and enjoyable space for thousands of players across our experiences.",
    features: [
      "Serve and protect a community of thousands of players",
      "Access to moderation tools and training resources",
      "Develop leadership and conflict resolution skills",
      "Be part of a close-knit moderation team",
      "Shape community guidelines and culture"
    ],
    icon: <ShieldCheckIcon className="size-8" />
  },
  {
    title: "Content Creator",
    description:
      "Help tell the MYSverse story. From social media to video production, content creators bring our community and experiences to life for a wider audience.",
    features: [
      "Create content across social media platforms",
      "Produce videos, graphics, and written content",
      "Collaborate with the team on campaigns and events",
      "Grow your creative portfolio and audience",
      "Access to exclusive behind-the-scenes content"
    ],
    icon: <CameraIcon className="size-8" />
  }
];

export interface JoinMethod {
  type: "email" | "discord" | "form" | "custom";
  label: string;
  description: string;
  href: string;
  icon: ReactNode;
  primary?: boolean;
}

export const joinMethods: JoinMethod[] = [
  {
    type: "discord",
    label: "Join our Discord",
    description: "Connect with the team and get started",
    href: "https://discord.com/invite/uPkrYWd",
    icon: <FontAwesomeIcon icon={faDiscord} className="size-5" />,
    primary: true
  },
  {
    type: "email",
    label: "Send us an email",
    description: "Reach out directly to the team",
    href: "mailto:yan@mysver.se",
    icon: <EnvelopeIcon className="size-5" />
  }
];
